### PR TITLE
Fix Alex timesheet tracking issue

### LINKED ISSUE #129: Timesheet shows negative tracking when it shouldn't
@aslotte is the unwitting recipient of this bug. :) 

Alex's timesheet had 80 "plus" hours for a 10-day pay period. However, when reviewing his timesheet, the tracking was shown as `-8` instead of `0` as expected. 

Luckily, I can recreate the whole timesheet in a test and then create a more localized version once I find the issue.

### PR DESCRIPTION
**Pull request by SeanKilleen**
Will resolve #129.

## Background

When getting the working days remaining, we subtract 1 if we've entered hours today and today is a weekday. This is so that if the timesheet is empty for that day, we assume it will be filled with 8 hours. If it's got any time in it, we assume time has been entered and update the tracking to reflect that.

## What's the problem?

When there are 0 weekdays left in the time period, we still perform this check. 

This means that if someone has entered time on the last day of the timesheet, we may return `-1` for the number of days remaining instead of `0`, thus throwing the tracking number off by 8 hours.

### CODE REVIEW

**Comment by SeanKilleen** [comment]
This was a fun little edge case!

File: src/classes/Loaders/EditModeLoader.ts [hunk 1]
```diff
@@ -14,7 +14,7 @@ export class EditModeLoader implements ITimesheetLoader {
 
   constructor(pageTitle: string, timesheetTable: Element) {
     this.pageTitle = pageTitle;
-    this.todayDate = moment();
+    this.todayDate = moment().startOf("day");
```
Comment (SeanKilleen) [inline src/classes/Loaders/EditModeLoader.ts]: ℹ️ Did this throughout the PR too because why not? Ensures we're working with the start of a given date so it can't be thrown off by a few hours' difference.

File: src/classes/Timesheet.ts [hunk 2]
```diff
@@ -91,6 +90,9 @@ export class Timesheet {
 
   public numberOfRemainingWorkDays = (): number => {
     let workingDaysLeft: number = this.weekDaysBetweenDates(this.todaysDate, this.timesheetEndDate);
+    if (workingDaysLeft === 0) {
+      return 0;
```
Comment (SeanKilleen) [inline src/classes/Timesheet.ts]: ℹ️ This missing code is what fixed the bug. If there are already 0 days left, stop and return 0 -- don't do the additional check.
